# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-15 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_essence',
            field=models.BooleanField(default=False, verbose_name=b'\xe5\x8a\xa0\xe7\xb2\xbe'),
        ),
    ]
