# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-16 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_banner_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='tie',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='users.Post', verbose_name=b'\xe5\xb8\x96\xe5\xad\x90'),
        ),
    ]
